import { useEffect, useRef, useState } from "react";
import type { Route } from "./+types/home";
import {
  fmtCompact,
  fmtInt,
  fmtUsd,
  getNetworkOverview,
  type NetworkOverview,
} from "../lib/analytics";
import { AreaChart, Bars, LineChart, StackedBars } from "../components/charts";

const SITE_URL = "https://nuroai.xyz";
const POLL_MS = 15_000;

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Nuro Data - Live Network Analytics" },
    {
      name: "description",
      content:
        "Live, aggregate-only data for the Nuro inference network: tokens generated, workers online, jobs, and contributor growth. No prompt or response content, ever.",
    },
    { property: "og:url", content: "https://data.nuroai.xyz" },
  ];
}

export default function Home() {
  const [data, setData] = useState<NetworkOverview | null>(null);
  const [error, setError] = useState(false);
  const [updatedAt, setUpdatedAt] = useState<Date | null>(null);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    let alive = true;
    const controller = new AbortController();

    const load = async () => {
      try {
        const next = await getNetworkOverview(controller.signal);
        if (!alive) return;
        setData(next);
        setError(false);
        setUpdatedAt(new Date());
      } catch {
        if (alive) setError(true);
      }
    };

    load();
    timer.current = setInterval(load, POLL_MS);
    return () => {
      alive = false;
      controller.abort();
      if (timer.current) clearInterval(timer.current);
    };
  }, []);

  const t = data?.totals;
  const live = data?.live;

  return (
    <div className="min-h-screen bg-black text-zinc-100">
      {/* header */}
      <header className="mx-auto max-w-5xl px-6 pt-10 pb-6">
        <div className="flex items-baseline justify-between">
          <div className="flex items-baseline gap-2">
            <span className="text-2xl font-semibold tracking-tight">nuro</span>
            <span className="font-mono text-xs text-zinc-500">/ data</span>
          </div>
          <a
            href={SITE_URL}
            className="font-mono text-xs text-zinc-500 transition hover:text-zinc-200"
          >
            nuroai.xyz
          </a>
        </div>

        {/* hero */}
        <div className="mt-10">
          <div className="font-mono text-6xl font-semibold tracking-tighter tabular-nums sm:text-7xl">
            {t ? fmtInt(t.tokensGenerated) : "\u2014"}
          </div>
          <p className="mt-2 font-mono text-xs text-zinc-500">
            tokens generated by the network
          </p>
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 pb-24">
        {/* live */}
        <Section title="live" updatedAt={updatedAt} error={error}>
          <div className="grid grid-cols-2 gap-px bg-zinc-900 sm:grid-cols-3 lg:grid-cols-6">
            <Stat live value={live ? String(live.workersOnline) : "\u2014"} label="workers online" />
            <Stat live value={live ? String(live.nativeOnline) : "\u2014"} label="native (gpu)" />
            <Stat live value={live ? String(live.browserOnline) : "\u2014"} label="browser" />
            <Stat
              value={live ? `${live.busyNow}/${live.workersOnline}` : "\u2014"}
              label="busy now"
            />
            <Stat value={t ? fmtInt(t.jobsCompleted) : "\u2014"} label="jobs completed" />
            <Stat value={t ? fmtUsd(t.settledUsd) : "\u2014"} label="settled (usd)" />
          </div>
        </Section>

        {/* network */}
        <Section title="network">
          <div className="grid gap-4 lg:grid-cols-2">
            <ChartCard
              title="jobs per day"
              legend={[
                { label: "native", color: "#d4d4d8" },
                { label: "browser", color: "#52525b" },
              ]}
            >
              {data ? (
                <StackedBars data={data.series.jobsPerDay} />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="tokens generated per day">
              {data ? (
                <AreaChart
                  hatchId="hatch-tokens"
                  data={data.series.tokensPerDay.map((d) => ({
                    date: d.date,
                    value: d.tokens,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="avg network speed (tok/s)">
              {data ? (
                <LineChart
                  step
                  data={data.series.speedPerDay.map((d) => ({
                    date: d.date,
                    value: d.tokPerSec,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="cumulative jobs">
              {data ? (
                <LineChart
                  data={runningTotal(
                    data.series.jobsPerDay.map((d) => ({
                      date: d.date,
                      value: d.native + d.browser,
                    })),
                  )}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
          </div>
        </Section>

        {/* users */}
        <Section title="users">
          <div className="mb-4 grid grid-cols-2 gap-px bg-zinc-900 sm:grid-cols-4">
            <Stat
              value={t ? fmtInt(t.registeredUsers) : "\u2014"}
              label="registered users"
            />
            <Stat
              value={
                data
                  ? fmtInt(
                      data.series.signupsPerDay.reduce((a, d) => a + d.count, 0),
                    )
                  : "\u2014"
              }
              label="signups (30d)"
            />
            <Stat
              value={t ? fmtCompact(t.tokensGenerated) : "\u2014"}
              label="tokens (all time)"
            />
            <Stat value={t ? fmtUsd(t.settledUsd) : "\u2014"} label="contributor payouts" />
          </div>
          <div className="grid gap-4 lg:grid-cols-2">
            <ChartCard title="new signups per day">
              {data ? (
                <Bars
                  data={data.series.signupsPerDay.map((d) => ({
                    date: d.date,
                    value: d.count,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
            <ChartCard title="cumulative users">
              {data ? (
                <AreaChart
                  hatchId="hatch-users"
                  data={data.series.cumulativeUsers.map((d) => ({
                    date: d.date,
                    value: d.total,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
          </div>
        </Section>

        <p className="mt-12 font-mono text-[11px] leading-relaxed text-zinc-600">
          Aggregate metrics only - no prompt or response content is ever recorded
          or shown. Updated live from the Nuro orchestrator.
        </p>
      </main>
    </div>
  );
}

// ---- pieces ---------------------------------------------------------------

function Section({
  title,
  children,
  updatedAt,
  error,
}: {
  title: string;
  children: React.ReactNode;
  updatedAt?: Date | null;
  error?: boolean;
}) {
  return (
    <section className="mt-12 first:mt-8">
      <div className="mb-4 flex items-center justify-between border-b border-zinc-800 pb-2">
        <h2 className="text-xl tracking-tight text-zinc-300">{title}</h2>
        {(updatedAt || error) && (
          <span className="flex items-center gap-1.5 font-mono text-[11px] text-zinc-500">
            <span
              className={`inline-block h-1.5 w-1.5 rounded-full ${
                error ? "bg-red-500" : "bg-emerald-500"
              }`}
            />
            {error
              ? "reconnecting"
              : `updated ${updatedAt?.toLocaleTimeString("en-US", {
                  hour12: false,
                })}`}
          </span>
        )}
      </div>
      {children}
    </section>
  );
}

function Stat({
  value,
  label,
  live,
}: {
  value: string;
  label: string;
  live?: boolean;
}) {
  return (
    <div className="bg-black p-4">
      <div className="font-mono text-2xl font-medium tabular-nums text-zinc-100">
        {value}
      </div>
      <div className="mt-1 flex items-center gap-1.5 font-mono text-[11px] text-zinc-500">
        {live && <span className="inline-block h-2 w-2 bg-emerald-500" />}
        {label}
      </div>
    </div>
  );
}

function ChartCard({
  title,
  legend,
  children,
}: {
  title: string;
  legend?: { label: string; color: string }[];
  children: React.ReactNode;
}) {
  return (
    <div className="border border-zinc-800 p-4">
      <div className="mb-3 flex items-center justify-between">
        <span className="font-mono text-xs text-zinc-400">{title}</span>
        {legend && (
          <span className="flex items-center gap-3">
            {legend.map((l) => (
              <span
                key={l.label}
                className="flex items-center gap-1.5 font-mono text-[10px] text-zinc-500"
              >
                <span
                  className="inline-block h-2 w-2"
                  style={{ background: l.color }}
                />
                {l.label}
              </span>
            ))}
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

function ChartSkeleton() {
  return <div className="h-[190px] w-full animate-pulse bg-zinc-900/60" />;
}

function runningTotal(
  data: { date: string; value: number }[],
): { date: string; value: number }[] {
  let sum = 0;
  return data.map((d) => {
    sum += d.value;
    return { date: d.date, value: sum };
  });
}
