import { useEffect, useRef, useState } from "react";
import type { Route } from "./+types/home";
import {
  fmtCompact,
  fmtInt,
  fmtUsd,
  getNetworkOverview,
  type NetworkOverview,
} from "../lib/analytics";
import { getStakingStats, type StakingStats } from "../lib/staking";
import {
  fmtPct,
  fmtPrice,
  getTokenMarket,
  type TokenMarket,
} from "../lib/price";
import { AreaChart, Bars, LineChart, StackedBars } from "../components/charts";

const SITE_URL = "https://nuroai.xyz";
const POLL_MS = 15_000;

export function meta({}: Route.MetaArgs) {
  return [
    { title: "Nuro Data - Live Network Analytics" },
    {
      name: "description",
      content:
        "Live, aggregate-only data for the Nuro inference network: tokens generated, workers online, jobs, and contributor growth. No prompt or response content, ever.",
    },
    { property: "og:url", content: "https://data.nuroai.xyz" },
  ];
}

export default function Home() {
  const [data, setData] = useState<NetworkOverview | null>(null);
  const [staking, setStaking] = useState<StakingStats | null>(null);
  const [market, setMarket] = useState<TokenMarket | null>(null);
  const [error, setError] = useState(false);
  const [updatedAt, setUpdatedAt] = useState<Date | null>(null);
  const timer = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    let alive = true;
    const controller = new AbortController();

    const load = async () => {
      try {
        const next = await getNetworkOverview(controller.signal);
        if (!alive) return;
        setData(next);
        setError(false);
        setUpdatedAt(new Date());
      } catch {
        if (alive) setError(true);
      }
      // On-chain staking read is independent of the orchestrator — a failure
      // here must never blank out the rest of the dashboard.
      try {
        const s = await getStakingStats(controller.signal);
        if (alive) setStaking(s);
      } catch {
        /* keep the last known value */
      }
      // Market data (DexScreener) is also independent; keep last value on error.
      try {
        const m = await getTokenMarket(controller.signal);
        if (alive) setMarket(m);
      } catch {
        /* keep the last known value */
      }
    };

    load();
    timer.current = setInterval(load, POLL_MS);
    return () => {
      alive = false;
      controller.abort();
      if (timer.current) clearInterval(timer.current);
    };
  }, []);

  const t = data?.totals;
  const live = data?.live;

  return (
    <div className="min-h-screen bg-black text-zinc-100">
      {/* header */}
      <header className="mx-auto max-w-5xl px-6 pt-10 pb-6">
        <div className="flex items-baseline justify-between">
          <div className="flex items-baseline gap-2">
            <span className="text-2xl font-semibold tracking-tight">nuro</span>
            <span className="font-mono text-xs text-zinc-500">/ data</span>
          </div>
          <a
            href={SITE_URL}
            className="font-mono text-xs text-zinc-500 transition hover:text-zinc-200"
          >
            nuroai.xyz
          </a>
        </div>

        {/* hero */}
        <div className="mt-10">
          <div className="font-mono text-6xl font-semibold tracking-tighter tabular-nums sm:text-7xl">
            {t ? fmtInt(t.tokensGenerated) : "\u2014"}
          </div>
          <p className="mt-2 font-mono text-xs text-zinc-500">
            tokens generated by the network
          </p>
        </div>

        {/* headline metrics */}
        <div className="mt-8 grid grid-cols-1 gap-px border border-zinc-800 bg-zinc-900 sm:grid-cols-3">
          <Headline
            value={staking ? `${fmtCompact(staking.nuroLocked)}` : "\u2014"}
            unit="$NURO"
            label="locked in staking pool"
          />
          <Headline
            value={t ? fmtInt(t.registeredUsers) : "\u2014"}
            label="total users"
          />
          <Headline
            live
            value={live ? fmtInt(live.workersOnline) : "\u2014"}
            label="total workers online"
          />
        </div>
      </header>

      <main className="mx-auto max-w-5xl px-6 pb-24">
        {/* live */}
        <Section title="live" updatedAt={updatedAt} error={error}>
          <div className="grid grid-cols-2 gap-px bg-zinc-900 sm:grid-cols-3 lg:grid-cols-6">
            <Stat live value={live ? String(live.workersOnline) : "\u2014"} label="workers online" />
            <Stat live value={live ? String(live.nativeOnline) : "\u2014"} label="native (gpu)" />
            <Stat live value={live ? String(live.browserOnline) : "\u2014"} label="browser" />
            <Stat
              value={live ? `${live.busyNow}/${live.workersOnline}` : "\u2014"}
              label="busy now"
            />
            <Stat value={t ? fmtInt(t.jobsCompleted) : "\u2014"} label="jobs completed" />
            <Stat value={t ? fmtUsd(t.settledUsd) : "\u2014"} label="settled (usd)" />
          </div>
        </Section>

        {/* $nuro market */}
        <Section title="$nuro market">
          <div className="border border-zinc-800">
            <div className="flex flex-col gap-4 border-b border-zinc-800 p-5 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <div className="flex items-baseline gap-3">
                  <span className="font-mono text-4xl font-semibold tabular-nums text-zinc-50 sm:text-5xl">
                    {market ? fmtPrice(market.priceUsd) : "\u2014"}
                  </span>
                  {market && market.priceChange.h24 >= 0 && (
                    <span className="font-mono text-sm tabular-nums text-emerald-400">
                      {fmtPct(market.priceChange.h24)}{" "}
                      <span className="text-zinc-600">24h</span>
                    </span>
                  )}
                </div>
                <p className="mt-2 font-mono text-[11px] text-zinc-500">
                  {market
                    ? `NURO / ${market.quoteSymbol} · ${market.dexId} · robinhood chain`
                    : "live price from dexscreener"}
                </p>
              </div>
              <a
                href={market?.url ?? "https://dexscreener.com"}
                target="_blank"
                rel="noreferrer"
                className="inline-flex w-fit items-center gap-1.5 border border-zinc-700 px-3 py-1.5 font-mono text-xs text-zinc-300 transition hover:border-zinc-500 hover:text-zinc-100"
              >
                trade on dexscreener {"\u2197"}
              </a>
            </div>

            <div className="grid grid-cols-2 gap-px bg-zinc-900 sm:grid-cols-4">
              <Stat
                value={market ? fmtUsd(market.marketCap || market.fdv) : "\u2014"}
                label="market cap"
              />
              <Stat
                value={market ? fmtUsd(market.volume24h) : "\u2014"}
                label="volume (24h)"
              />
              <Stat
                value={market ? fmtUsd(market.liquidityUsd) : "\u2014"}
                label="liquidity"
              />
              <Stat value={market ? fmtUsd(market.fdv) : "\u2014"} label="fdv" />
            </div>

            <div className="grid grid-cols-4 gap-px border-t border-zinc-900 bg-zinc-900">
              <Change label="5m" value={market?.priceChange.m5} />
              <Change label="1h" value={market?.priceChange.h1} />
              <Change label="6h" value={market?.priceChange.h6} />
              <Change label="24h" value={market?.priceChange.h24} />
            </div>
          </div>
        </Section>

        {/* network */}
        <Section title="network">
          <div className="grid gap-4 lg:grid-cols-2">
            <ChartCard
              title="jobs per day"
              legend={[
                { label: "native", color: "#d4d4d8" },
                { label: "browser", color: "#52525b" },
              ]}
            >
              {data ? (
                <StackedBars data={data.series.jobsPerDay} />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="tokens generated per day">
              {data ? (
                <AreaChart
                  hatchId="hatch-tokens"
                  data={data.series.tokensPerDay.map((d) => ({
                    date: d.date,
                    value: d.tokens,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="avg network speed (tok/s)">
              {data ? (
                <LineChart
                  step
                  data={data.series.speedPerDay.map((d) => ({
                    date: d.date,
                    value: d.tokPerSec,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>

            <ChartCard title="cumulative jobs">
              {data ? (
                <LineChart
                  data={runningTotal(
                    data.series.jobsPerDay.map((d) => ({
                      date: d.date,
                      value: d.native + d.browser,
                    })),
                  )}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
          </div>
        </Section>

        {/* users */}
        <Section title="users">
          <div className="mb-4 grid grid-cols-2 gap-px bg-zinc-900 sm:grid-cols-4">
            <Stat
              value={t ? fmtInt(t.registeredUsers) : "\u2014"}
              label="registered users"
            />
            <Stat
              value={
                data
                  ? fmtInt(
                      data.series.signupsPerDay.reduce((a, d) => a + d.count, 0),
                    )
                  : "\u2014"
              }
              label="signups (30d)"
            />
            <Stat
              value={t ? fmtCompact(t.tokensGenerated) : "\u2014"}
              label="tokens (all time)"
            />
            <Stat value={t ? fmtUsd(t.settledUsd) : "\u2014"} label="contributor payouts" />
          </div>
          <div className="grid gap-4 lg:grid-cols-2">
            <ChartCard title="new signups per day">
              {data ? (
                <Bars
                  data={data.series.signupsPerDay.map((d) => ({
                    date: d.date,
                    value: d.count,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
            <ChartCard title="cumulative users">
              {data ? (
                <AreaChart
                  hatchId="hatch-users"
                  data={data.series.cumulativeUsers.map((d) => ({
                    date: d.date,
                    value: d.total,
                  }))}
                />
              ) : (
                <ChartSkeleton />
              )}
            </ChartCard>
          </div>
        </Section>

        <p className="mt-12 font-mono text-[11px] leading-relaxed text-zinc-600">
          Aggregate metrics only - no prompt or response content is ever recorded
          or shown. Updated live from the Nuro orchestrator.
        </p>
      </main>
    </div>
  );
}

// ---- pieces ---------------------------------------------------------------

function Section({
  title,
  children,
  updatedAt,
  error,
}: {
  title: string;
  children: React.ReactNode;
  updatedAt?: Date | null;
  error?: boolean;
}) {
  return (
    <section className="mt-12 first:mt-8">
      <div className="mb-4 flex items-center justify-between border-b border-zinc-800 pb-2">
        <h2 className="text-xl tracking-tight text-zinc-300">{title}</h2>
        {(updatedAt || error) && (
          <span className="flex items-center gap-1.5 font-mono text-[11px] text-zinc-500">
            <span
              className={`inline-block h-1.5 w-1.5 rounded-full ${
                error ? "bg-red-500" : "bg-emerald-500"
              }`}
            />
            {error
              ? "reconnecting"
              : `updated ${updatedAt?.toLocaleTimeString("en-US", {
                  hour12: false,
                })}`}
          </span>
        )}
      </div>
      {children}
    </section>
  );
}

function Headline({
  value,
  unit,
  label,
  live,
}: {
  value: string;
  unit?: string;
  label: string;
  live?: boolean;
}) {
  return (
    <div className="bg-black px-5 py-6">
      <div className="flex items-baseline gap-2">
        <span className="font-mono text-3xl font-semibold tabular-nums text-zinc-50 sm:text-4xl">
          {value}
        </span>
        {unit && (
          <span className="font-mono text-sm text-zinc-500">{unit}</span>
        )}
      </div>
      <div className="mt-2 flex items-center gap-1.5 font-mono text-[11px] uppercase tracking-wide text-zinc-500">
        {live && (
          <span className="inline-block h-2 w-2 animate-pulse bg-emerald-500" />
        )}
        {label}
      </div>
    </div>
  );
}

function Change({ label, value }: { label: string; value?: number }) {
  // Only surface positive momentum — negative changes render as a neutral dash.
  const positive = typeof value === "number" && value >= 0;
  return (
    <div className="bg-black p-4">
      <div
        className={`font-mono text-lg font-medium tabular-nums ${
          positive ? "text-emerald-400" : "text-zinc-600"
        }`}
      >
        {positive ? fmtPct(value as number) : "\u2014"}
      </div>
      <div className="mt-1 font-mono text-[11px] text-zinc-500">{label}</div>
    </div>
  );
}

function Stat({
  value,
  label,
  live,
}: {
  value: string;
  label: string;
  live?: boolean;
}) {
  return (
    <div className="bg-black p-4">
      <div className="font-mono text-2xl font-medium tabular-nums text-zinc-100">
        {value}
      </div>
      <div className="mt-1 flex items-center gap-1.5 font-mono text-[11px] text-zinc-500">
        {live && <span className="inline-block h-2 w-2 bg-emerald-500" />}
        {label}
      </div>
    </div>
  );
}

function ChartCard({
  title,
  legend,
  children,
}: {
  title: string;
  legend?: { label: string; color: string }[];
  children: React.ReactNode;
}) {
  return (
    <div className="border border-zinc-800 p-4">
      <div className="mb-3 flex items-center justify-between">
        <span className="font-mono text-xs text-zinc-400">{title}</span>
        {legend && (
          <span className="flex items-center gap-3">
            {legend.map((l) => (
              <span
                key={l.label}
                className="flex items-center gap-1.5 font-mono text-[10px] text-zinc-500"
              >
                <span
                  className="inline-block h-2 w-2"
                  style={{ background: l.color }}
                />
                {l.label}
              </span>
            ))}
          </span>
        )}
      </div>
      {children}
    </div>
  );
}

function ChartSkeleton() {
  return <div className="h-[190px] w-full animate-pulse bg-zinc-900/60" />;
}

function runningTotal(
  data: { date: string; value: number }[],
): { date: string; value: number }[] {
  let sum = 0;
  return data.map((d) => {
    sum += d.value;
    return { date: d.date, value: sum };
  });
}
